### ISSUE TITLE
More unused files

### ISSUE THREAD

**Issue by ak2yny** [EthanReed517/Marvel-Mods-Batch-Scripts#4]
We identified the unused engb files when making translations. They are in the attached file (includes a few other files, other than the unused engbs). Should they be added to the cleanup script?
[exclude_leftover.txt](https://github.com/EthanReed517/Marvel-Mods-Batch-Scripts/files/10466496/exclude_leftover.txt)

**Comment by ak2yny** [comment]
I just found an old list of mine, which includes the [leftover powerstyles](https://github.com/EthanReed517/Marvel-Mods-Batch-Scripts/files/10472142/leftover_ps.txt) in the powerstyles folder. They don't all have engb files, but the ones which do, are duplicates from the [exclude_leftover](https://github.com/EthanReed517/Marvel-Mods-Batch-Scripts/files/10466496/exclude_leftover.txt) list.

**Comment by EthanReed517** [comment]
I think that this would be a good idea to include. I planned to eventually include something similar for XML2 to help clear up some files that will be changed for the X2UP.

**Comment by EthanReed517** [comment]
@ak2yny if you can make these changes (on the MUA1 side), I'll release the latest version of everything.

**Comment by ak2yny** [comment]
Done: https://github.com/EthanReed517/Marvel-Mods-Batch-Scripts/commit/f1bf1677aa8d644de72b53d4e3d537496a3644c2
